name: Publish to npm
author: pascalgn
description: Automatically publish new versions to npm

inputs:
  commit_pattern:
    description: The pattern that matches version update commits.
    required: false
  tag_name:
    description: The name of the tag that you want to create for the version.
    required: false
  tag_message:
    description: The message of the tag that you want to create for the version.
    required: false
  commit_user:
    description: Te user name for making git commit.
    required: false
  commit_email:
    description: The email address for making git commit.
    required: false
  publish_with:
    description: Publish the package with npm or yarn.
    required: false
runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: blue
